image: php:7.1.1
pipelines:
  default:
    - step:
        caches:
          - composer
        script:
        - apt-get update && apt-get install -y unzip git 
        - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
        - rm composer.lock
        - composer install
        - vendor/bin/phplint ./
        - vendor/bin/parallel-lint --exclude vendor .
        - echo "Enviamos el codigo limpio"
        - touch ~/.ssh/ccbb_rsa.b64
        - chmod 600 ~/.ssh/ccbb_rsa.b64
        - echo $CodeCommitKey >> ~/.ssh/ccbb_rsa.b64
        - cat ~/.ssh/ccbb_rsa.b64|/usr/bin/base64 -d > ~/.ssh/ccbb_rsa
        - chmod 400 ~/.ssh/ccbb_rsa
        - echo $CodeCommitConfig  > ~/.ssh/config.b64
        - cat ~/.ssh/config.b64
        - cat ~/.ssh/config.b64 |/usr/bin/base64 -d > ~/.ssh/config
        - set +e
        - ssh -t -t -o StrictHostKeyChecking=no $CodeCommitHost
        - set -e
        - git remote add codecommit ssh://$CodeCommitRepo
        - git push codecommit $BITBUCKET_BRANCH       
